export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'

export const SUCCESS_LOAD_FRIENDS_LIST = 'SUCCESS_LOAD_FRIENDS_LIST'
export const ERROR_LOAD_FRIENDS_LIST = 'ERROR_LOAD_FRIENDS_LIST'

export const SUCCESS_LOAD_USER_DATA = 'SUCCESS_LOAD_USER_DATA'
export const ERROR_LOAD_USER_DATA = 'ERROR_LOAD_USER_DATA'